Feature/pegout status service
rsksmart/2wp-api pull request #114
Opened 2022-05-19 04:19 UTC by ronaldsg20

2022-05-26 19:10 UTC, josedahlquist requested changes

2022-05-26 19:10 UTC, josedahlquist commented on src/dependency-injection-handler.ts
> +    .inScope(BindingScope.SINGLETON);
```suggestion
    app
      .bind(ServicesBindings.RSK_BLOCK_PROCESSOR_PUBLISHER)
      .toClass(NodeBridgeDataProvider)
      .inScope(BindingScope.SINGLETON);
```

2022-05-26 19:10 UTC, josedahlquist commented on src/models/rsk/pegout-status-data-model.ts
> +  static fromPegoutStatusDbDataModel(model: PegoutStatusDbDataModel):PegoutStatusAppDataModel {
does it need to be from `PegoutStatusDbDataModel` implementation or could it just be from `PegoutStatusDataModel` interface?

2022-05-26 19:10 UTC, josedahlquist commented on src/services/pegout-status/pegout-status.service.ts
> +            pegoutStatusDataService: PegoutStatusMongoDbDataService,
We should use the interface everytime we can
```suggestion
            pegoutStatusDataService: PegoutStatusDataService,
```

2022-05-30 14:27 UTC, alexjavabraz approved these changes
SGTM

2022-05-30 15:44 UTC, merged