Refactor pegout status service
rsksmart/2wp-api pull request #126
Opened 2022-06-02 19:28 UTC by alexjavabraz

This pr will not finish the solves the Refactor PegoutStatusService to handle pegouts that are not yet registered in the db, this is only the first part to complete the task. 
We need to finish the PegoutDataProcessor.process method to do the second part of that task.

2022-06-06 16:05 UTC, josedahlquist reviewed
Besides my comments I suggest reviewing the formatting, seems like you are missing some whitespaces here and there... we may solve this lately using formatting tools but if you can start doing it on your own, the future formatting code changes could be simpler.

2022-06-06 18:08 UTC, jeremy-then commented on src/services/pegout-status/pegout-status.service.ts
> +        let pegoutStatus: PegoutStatusAppDataModel = new PegoutStatusAppDataModel();
I agreed. It also caught my attention the logic duplication.

2022-06-07 20:03 UTC, jeremy-then requested changes

2022-06-07 20:21 UTC, jeremy-then approved these changes

2022-06-07 20:21 UTC, jeremy-then commented on src/services/pegout-data.processor.ts
> +  public async fillRequestReceivedStatus(extendedBridgeTx: ExtendedBridgeTx, releaseRequestReceivedEvent: BridgeEvent):Promise<PegoutStatusDbDataModel> {
The extendedBridgeTx already includes the releaseRequestReceivedEvent, so, let's only use the extendedBridgeTx. Also, I suggest changing the function signature to:

public static async getRequestReceivedStatus(extendedBridgeTx: ExtendedBridgeTx):Promise<PegoutStatusDbDataModel> ...

Maybe put getRequestReceivedStatus in another file like Jose suggested?

2022-06-08 00:49 UTC, ronaldsg20 approved these changes

2022-06-08 12:49 UTC, merged