Avoid error 500 when only one address fail search on blockbook
rsksmart/2wp-api pull request #159
Opened 2022-11-07 17:46 UTC by alexjavabraz

2022-11-08 20:52 UTC, josedahlquist requested changes

2022-11-08 20:52 UTC, josedahlquist commented on src/services/unused-address.service.ts
> +        .then((bitcoinAddressList: BitcoinAddress[]) => {
If you are going to await for each address then don't do a Promise.all.
Choose one or the other

2022-11-17 22:38 UTC, ronaldsg20 approved these changes

2022-11-22 13:44 UTC, hard75 approved these changes
delete code correct

2022-12-20 22:45 UTC, closed without merging